### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/chem_search_vis#1]
Following the instructions in the README:

```
root@chembl:/data/chembl10.demo/siren-kibi# ./bin/investigate install-plugin 'https://github.com/sirensolutions/chem_search_vis/releases/download/v2.0/v2.0.zip'

 ERROR  unknown command install-plugin

  Usage: bin/investigate [command=serve] [options]
```

**Comment by colmose** [comment]
I think it should be `./bin/investigate-plugin install 'https://github.com/sirensolutions/chem_search_vis/releases/download/v2.0/v2.0.zip'`

**Comment by emepyc** [comment]
Apologies and thanks @colmose for commenting.
This has now been fixed in the README
