### ISSUE TITLE
Under what SLA do we run chemical search as a public service?

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/chem_search_vis#2]
I see in the README it says:

```Siren provides a public site available for calculating these fingerprints at https://api.chemicalfingerprint.siren.io, but you can deploy your own service and use it in the plugin```

What SLA are we running this under?

**Comment by jccq** [comment]
no sla specifically at the moment we would define one if someone ever was
to purchase our public service

Giovanni Tummarello
CPO, Founder, Siren
A Unit 4, GTC, Mervue Park, Galway, Ireland
D +353 91704885
<+353+91704885?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
M +353 87 1272938
<+353+87+1272938?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
E giovanni.tummarello@siren.io  <giovanni.tummarello@siren.io> W
http://www.siren.io/
<http://www.siren.io/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.youtube.com/channel/UCKGsC-vD28r7hW6T9QspKPA?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.facebook.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/11117365?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://conferences.oreilly.com/strata/strata-ca?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren
will be atStrata Data Conference (March 6-8, 2018, San Jose, CA)
<https://conferences.oreilly.com/strata/strata-ca?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-london-2018/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren will be atBig Data & Analytics for Pharma Summit (March 21-22, 2018,
London)
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-london-2018/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by andrewgdotcom** [comment]
How do you purchase a public service that is already freely available?

**Comment by jccq** [comment]
you purchase the SLA in fact. (this is pretty standard rally? no money no
SLA..  = best effort money then i guearantee a service)

Giovanni Tummarello
CPO, Founder, Siren
A Unit 4, GTC, Mervue Park, Galway, Ireland
D +353 91704885
<+353+91704885?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
M +353 87 1272938
<+353+87+1272938?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
E giovanni.tummarello@siren.io  <giovanni.tummarello@siren.io> W
http://www.siren.io/
<http://www.siren.io/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.youtube.com/channel/UCKGsC-vD28r7hW6T9QspKPA?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.facebook.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/11117365?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://conferences.oreilly.com/strata/strata-ca?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren
will be atStrata Data Conference (March 6-8, 2018, San Jose, CA)
<https://conferences.oreilly.com/strata/strata-ca?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-london-2018/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren will be atBig Data & Analytics for Pharma Summit (March 21-22, 2018,
London)
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-london-2018/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by jccq** [comment]
To close this, please write something along the line of  "for demo purpose, Siren runs a service.. etc etc. The service is provided as a courtesy on a best effort basis, for production deployment you should be running your service internally."

**Comment by emepyc** [comment]
That sentence has been added to the README of the package
