### ISSUE TITLE
Worth embedding the fingerprint service into investigate?

### ISSUE THREAD

**Issue by Blakko** [sirensolutions/chem_search_vis#3]
I saw that there is a nodejs library to handle molecular fingerprint, might be worth exploring if investigate can expose the service without having to maintain a public one ourselves?

**Comment by jccq** [comment]
we wont maintain a public service,we simply show how it works as reference people will run their own.

**Comment by jccq** [comment]
@emepyc for possible other comments

**Comment by emepyc** [comment]
Thanks @Blakko . I don't know of any nodejs library to do molecular fingerprints, did you find any? We are doing it using the RDKit library.

**Comment by Blakko** [comment]
It should be a wrapper for the RDKit library https://github.com/cheminfo/RDKitjs

**Comment by emepyc** [comment]
Ah, ok. You still need rdkit installed, which is not trivial for non-linux systems (this is why we wrap the api in a docker container). We may want to explore the js wrapper, but at first sight looks a bit less mature than the python one we use at the moment. Thanks for the heads up!
