### ISSUE TITLE
Incorrect Kibana version

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/chem_search_vis#4]
When installing the plugin into the latest snapshot, I get the following error:

```
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [chem_search_vis]. Expected [5.6.7]; found [5.6.4]"
```

**Comment by colmose** [comment]
Sentinl has a `--version=5.6.7` flag you can pass when building. Check out the [Gulpfile of sentinl-private](https://github.com/sirensolutions/sentinl-private/blob/master/gulpfile.js) and [this helper script](https://github.com/sirensolutions/sentinl-private/blob/master/scripts/createReleases.sh).

**Comment by szydan** [comment]
~~Weird as sentinl master is on 5.6.7
@andrewgdotcom from where you took it?~~

**Comment by andrewgdotcom** [comment]
What has sentinl got to do with it?

**Comment by colmose** [comment]
Just saying it might help to replicate how Sentinl generates different packages (for different versions) if there are going to be multiple releases of essentially the same code for separate kibana versions.

**Comment by szydan** [comment]
@andrewgdotcom sorry I thought it was about sentinl

**Comment by emepyc** [comment]
@andrewgdotcom I have now updated the v2.0 bundle, could you please try again?
